public class testcontrol_lowercase {
    public void method() {
        string var01 = '';
        if (var01 == '') {
        }
        
        if (var01 == '') {
        } else {
        }
        
        for (string var02 : new string[] {}) {
        }
        
        for (;;) {
        }

        for (integer var03 = 0;;) {
        }

        for (; var01 == '';) {
        }
        
        for (;; var01 = '') {
        }
       
        while (var01 == '') system.debug('do nothing');
        while (var01 == '') {
            system.debug('do nothing');
        }
        
        do {} while (var01 == '');
        do {
            system.debug('do nothing');
        } 
        while (var01 == '');
        
        try {
            system.debug('do nothing');
        } catch (Exception e) {
            throw e;
        }
        
        for (;;) {
           for (;;) {
               break;
               continue;
           }
        }
    }
}
